project_name: oas-ci-agent
project_description: instala agentes de ci
project_purpose: los agentes de ci son necesarios para el sistema de ci
programming_language:
project_framework: ""
organizational_unit: Interno
package_dependencies:
- docker
build_dependencies:
- gcc
- make
- ruby
- rpm-build
- ruby-devel
sign_package: true
