project_name: oas-ci-agent
project_description: instala agentes de ci
project_purpose: los agentes de ci son necesarios para el sistema de ci
organizational_unit: Plataforma
package_dependencies:
  os:
  - docker
